version = 0.1

[default.deploy.parameters]
stack_name = "brothers-beats-dev"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
region = "eu-west-1"
confirm_changeset = true

[dev.deploy.parameters]
stack_name = "brothers-beats-dev"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
region = "eu-west-1"
confirm_changeset = true
parameter_overrides = "Environment=dev FrontendUrl=http://localhost:3000 ExtraCorsOrigins=https://brothers-beats.vercel.app GoogleAuthEnabled=false"

[prod.deploy.parameters]
stack_name = "brothers-beats-prod"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
region = "eu-west-1"
confirm_changeset = true
parameter_overrides = "Environment=prod FrontendUrl=https://www.brothersbeats.events ExtraCorsOrigins=https://brothersbeats.events GoogleAuthEnabled=false"
